### ISSUE TITLE
`DefaultEnvironment` fails to flush logs as it tries to use `AgentSink`

### ISSUE THREAD

**Issue by uldissturms** [awslabs/aws-embedded-metrics-node#6]
Hi,

This is more of a question than a bug.

Context:
We have added embedded metrics to our lambda stack that's using `serverless` and `serverless-offline` to run locally.

Issue:
When run locally (without `AWS_LAMBDA_FUNCTION_NAME` set) it defaults to `DefaultEnvironment` and kills the `serverless-offline` thread when `.flush()` is called because of unhandled promise rejection on another thread. It seems that default environment expect an `AgentSink` to be present. Is that expected?

Steps to reproduce:
```js
  const defaultEnv = new DefaultEnvironment();
  const defaultLogger = createLogger(() => Promise.resolve(defaultEnv));
  defaultLogger.flush()
```

**Comment by jaredcnance** [comment]
Thanks for opening this issue. Yes, the expected behavior is that if we're not running in a Lambda function (no `AWS_LAMBDA_FUNCTION_NAME` is set), we will fall back to using the AgentSink which attempts to establish a TCP connection with the CloudWatch agent. This allows us to support any runtime environment where the agent can be installed (K8s, ECS, Fargate etc.). That said it shouldn't be killing your process or preventing your app from running as expected.

Can you help me understand this statement a bit better:

> kills the serverless-offline thread when .flush() is called

It shouldn't be killing any "threads" since Node.js runs in a single-threaded event loop. However, I suspect what you're seeing is because the flush call is not awaited ([`flush()`](https://github.com/awslabs/aws-embedded-metrics-node/blob/master/src/logger/MetricsLogger.ts#L39) is async) and there is no error handler attached to the promise. You could change your code to this:

```ts
  const defaultEnv = new DefaultEnvironment();
  const defaultLogger = createLogger(() => Promise.resolve(defaultEnv));
  try {
    await defaultLogger.flush()
  } catch(error) { /* ... */ }
```

or this:

```ts
const defaultEnv = new DefaultEnvironment();
const defaultLogger = createLogger(() => Promise.resolve(defaultEnv));
defaultLogger.flush().catch(error => /* ... */ );
```

However, if your goal is to run on Lambda and you don't want to use the provided logger factory, then you can just use the Lambda environment rather than the default:

```ts
const lambdaEnv = new LambdaEnvironment();
const defaultLogger = createLogger(() => Promise.resolve(lambdaEnv));
await defaultLogger.flush(); 
// you technically don't _need_ to await this flush since there is no asyncio happening
// and the environment has already been resolved
```

**Comment by uldissturms** [comment]
Hi @jaredcnance. Thanks for having a look. I've opened #7 to highlight and fix the issue with unhandled rejections. I could find three issues with the current solutions:
* promise in `AgentSink.getSocketClient` that could get rejected and not handled called from constructor
* promise in `TcpClient.sendMessage` was not rejected on `this.socket.once('error', ...)`
* original error objects not passed along to `Promise.reject` calls in `TcpClient` made it harder to track down the networking issue from code using this package.

**Comment by uldissturms** [comment]
I also had trouble with the local docker setup for running tests locally `npm run integ` returned:
```bash
2019/11/26 12:18:28 Configuration validation first phase failed. Agent version: 1.232309.0. Verify the JSON input is only using features supported by this version.

2019/11/26 12:18:28 I! Return exit error: exit code=1
2019/11/26 12:18:28 E! Cannot translate JSON config into TOML, ERROR is exit status 1
```
Also the CI build output from AWS CodeBuild seems to be login protected?

**Comment by jaredcnance** [comment]
Thanks for the PR! The integration tests require valid aws credentials which is likely the issue but I will take a closer look later. Addressed your other comments in the PR.

**Comment by uldissturms** [comment]
#7 closes this issue.
