### ISSUE TITLE
Runtime Validations

### ISSUE THREAD

**Issue by madsbrunn** [awslabs/aws-embedded-metrics-node#68]
allowed:

`putDimensions({ Method: "GET", StatusCode: "200" })`

not allowed:

`putDimensions({ Method: "GET", StatusCode: 200 })`

**Comment by jaredcnance** [comment]
This is enforced via type annotations.

https://github.com/awslabs/aws-embedded-metrics-node/blob/d15858a54ab5717ebecaa04044b25d693f3ee654/src/logger/MetricsLogger.ts#L79

However, I understand that there is a need for runtime validations which is a bigger feature than individual validations. We don’t currently have any runtime validations that throw. Since we don’t currently have an open issue for this, I’ll re-purpose this issue.

**Comment by madsbrunn** [comment]
An runtime validation of dimension values (or at least a warning) would have saved me from some head scratching. It was only until I read the specification that I figured out why some of my metrics didn't show up in cloudwatch.
