### ISSUE TITLE
putMetric doesn't flush after 100 elements are added

### ISSUE THREAD

**Issue by matdumsa** [awslabs/aws-embedded-metrics-node#97]
The README mentions that "If more metric values are added than are supported by the format, the logger will be flushed to allow for new metric values to be captured." but this doesn't seem true if I trust the output of my program using the library and [the code I could read](https://github.com/awslabs/aws-embedded-metrics-node/blob/fe141e5b0f58d24b5e4d1a66716ec13e6d784872/src/logger/MetricValues.ts#L32)

This leads output to go above 100 leading to ignored entries.

**Comment by khangly** [comment]
I have verified this behavior, in the [Specification: Embedded metric format](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_metricdirective), it says
> **Metrics**— An array of [MetricDefinition](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_structure_metricdefinition) objects. This array MUST NOT contain more than 100 MetricDefinition objects.

#26 implements that constraint correctly. However, sometimes I got metric not appearing even though the logs were there. Upon doing some more verification, the issue is with the metric values. As long as one of the metric in your log has more than 100 values, all the metrics in that log will not get published.
